package com.movie.model;

// Generated Mar 31, 2014 2:57:31 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Moviedetails generated by hbm2java
 */
@Entity
@Table(name = "moviedetails", catalog = "moviedb")
public class Moviedetails implements java.io.Serializable {

	private String movieId;
	private String movieName;
	private Date movieReleaseDate;
	private String movieDirector;
	private String movieProducer;
	private String movieType;
	private String movieMusicDirector;
	private String movieStatus;
	private Date cdate=new Date();

	public Moviedetails() {
	}

	public Moviedetails(String movieId, Date cdate) {
		this.movieId = movieId;
		this.cdate = cdate;
	}

	public Moviedetails(String movieId, String movieName,
			Date movieReleaseDate, String movieDirector, String movieProducer,
			String movieType, String movieMusicDirector, String movieStatus,
			Date cdate) {
		this.movieId = movieId;
		this.movieName = movieName;
		this.movieReleaseDate = movieReleaseDate;
		this.movieDirector = movieDirector;
		this.movieProducer = movieProducer;
		this.movieType = movieType;
		this.movieMusicDirector = movieMusicDirector;
		this.movieStatus = movieStatus;
		this.cdate = cdate;
	}

	@Id
	@Column(name = "movieId", unique = true, nullable = false, length = 10)
	public String getMovieId() {
		return this.movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	@Column(name = "movieName", length = 20)
	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "movieReleaseDate", length = 10)
	public Date getMovieReleaseDate() {
		return this.movieReleaseDate;
	}

	public void setMovieReleaseDate(Date movieReleaseDate) {
		this.movieReleaseDate = movieReleaseDate;
	}

	@Column(name = "movieDirector", length = 20)
	public String getMovieDirector() {
		return this.movieDirector;
	}

	public void setMovieDirector(String movieDirector) {
		this.movieDirector = movieDirector;
	}

	@Column(name = "movieProducer", length = 20)
	public String getMovieProducer() {
		return this.movieProducer;
	}

	public void setMovieProducer(String movieProducer) {
		this.movieProducer = movieProducer;
	}

	@Column(name = "movieType", length = 20)
	public String getMovieType() {
		return this.movieType;
	}

	public void setMovieType(String movieType) {
		this.movieType = movieType;
	}

	@Column(name = "movieMusicDirector", length = 20)
	public String getMovieMusicDirector() {
		return this.movieMusicDirector;
	}

	public void setMovieMusicDirector(String movieMusicDirector) {
		this.movieMusicDirector = movieMusicDirector;
	}

	@Column(name = "movieStatus", length = 10)
	public String getMovieStatus() {
		return this.movieStatus;
	}

	public void setMovieStatus(String movieStatus) {
		this.movieStatus = movieStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cdate", nullable = false, length = 19)
	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	@Override
	public String toString() {
		return "Moviedetails [movieId=" + movieId + ", movieName=" + movieName
				+ ", movieReleaseDate=" + movieReleaseDate + ", movieDirector="
				+ movieDirector + ", movieProducer=" + movieProducer
				+ ", movieType=" + movieType + ", movieMusicDirector="
				+ movieMusicDirector + ", movieStatus=" + movieStatus
				+ ", cdate=" + cdate + "]";
	}

}
