package com.movie.model;
// Generated Mar 31, 2014 2:57:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paymentdetails generated by hbm2java
 */
@Entity
@Table(name="paymentdetails"
    ,catalog="moviedb"
)
public class Paymentdetails  implements java.io.Serializable {


     private String paymentId;
     private String uname;
     private String bookingId;
     private String paymentType;
     private String status;
     private Date bdate;

    public Paymentdetails() {
    }

	
    public Paymentdetails(String paymentId, Date bdate) {
        this.paymentId = paymentId;
        this.bdate = bdate;
    }
    public Paymentdetails(String paymentId, String uname, String bookingId, String paymentType, String status, Date bdate) {
       this.paymentId = paymentId;
       this.uname = uname;
       this.bookingId = bookingId;
       this.paymentType = paymentType;
       this.status = status;
       this.bdate = bdate;
    }
   
     @Id 

    
    @Column(name="PaymentId", unique=true, nullable=false, length=15)
    public String getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    
    @Column(name="uName", length=20)
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }

    
    @Column(name="bookingId", length=15)
    public String getBookingId() {
        return this.bookingId;
    }
    
    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }

    
    @Column(name="paymentType", length=20)
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bdate", nullable=false, length=19)
    public Date getBdate() {
        return this.bdate;
    }
    
    public void setBdate(Date bdate) {
        this.bdate = bdate;
    }




}


