package com.movie.model;
// Generated Mar 31, 2014 2:57:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Runningmovie generated by hbm2java
 */
@Entity
@Table(name="runningmovie"
    ,catalog="moviedb"
)
public class Runningmovie  implements java.io.Serializable {


     private String runningId;
     private String movieId;
     private String hallId;
     private Date startDate;
     private Date endDate;
     private Integer noOfShow;
     private String city;
     private String status;

    public Runningmovie() {
    }

	
    public Runningmovie(String runningId, Date startDate, Date endDate) {
        this.runningId = runningId;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Runningmovie(String runningId, String movieId, String hallId, Date startDate, Date endDate, Integer noOfShow, String city, String status) {
       this.runningId = runningId;
       this.movieId = movieId;
       this.hallId = hallId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.noOfShow = noOfShow;
       this.city = city;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="runningId", unique=true, nullable=false, length=15)
    public String getRunningId() {
        return this.runningId;
    }
    
    public void setRunningId(String runningId) {
        this.runningId = runningId;
    }

    
    @Column(name="movieId", length=20)
    public String getMovieId() {
        return this.movieId;
    }
    
    public void setMovieId(String movieId) {
        this.movieId = movieId;
    }

    
    @Column(name="hallId", length=20)
    public String getHallId() {
        return this.hallId;
    }
    
    public void setHallId(String hallId) {
        this.hallId = hallId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="startDate", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="endDate", nullable=false, length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="noOfShow")
    public Integer getNoOfShow() {
        return this.noOfShow;
    }
    
    public void setNoOfShow(Integer noOfShow) {
        this.noOfShow = noOfShow;
    }

    
    @Column(name="city", length=10)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="status", length=30)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


