package com.movie.model;
// Generated Mar 31, 2014 2:57:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Showdetails generated by hbm2java
 */
@Entity
@Table(name="showdetails"
    ,catalog="moviedb"
)
public class Showdetails  implements java.io.Serializable {


     private String showDetailId;
     private Date showDate;
     private String hallId;
     private String movieid;
     private String showtime;
     private String goldtype;
     private Integer goldnoofseats;
     private Integer goldprice;
     private String silvertype;
     private Integer silvernoofseats;
     private Integer silverprice;
     private String platinumtype;
     private Integer platinumnoofseats;
     private Integer platinumprice;
     private String remarks;

    public Showdetails() {
    }

	
    public Showdetails(String showDetailId, Date showDate) {
        this.showDetailId = showDetailId;
        this.showDate = showDate;
    }
    public Showdetails(String showDetailId, Date showDate, String hallId, String movieid, String showtime, String goldtype, Integer goldnoofseats, Integer goldprice, String silvertype, Integer silvernoofseats, Integer silverprice, String platinumtype, Integer platinumnoofseats, Integer platinumprice, String remarks) {
       this.showDetailId = showDetailId;
       this.showDate = showDate;
       this.hallId = hallId;
       this.movieid = movieid;
       this.showtime = showtime;
       this.goldtype = goldtype;
       this.goldnoofseats = goldnoofseats;
       this.goldprice = goldprice;
       this.silvertype = silvertype;
       this.silvernoofseats = silvernoofseats;
       this.silverprice = silverprice;
       this.platinumtype = platinumtype;
       this.platinumnoofseats = platinumnoofseats;
       this.platinumprice = platinumprice;
       this.remarks = remarks;
    }
   
     @Id 

    
    @Column(name="ShowDetailId", unique=true, nullable=false, length=15)
    public String getShowDetailId() {
        return this.showDetailId;
    }
    
    public void setShowDetailId(String showDetailId) {
        this.showDetailId = showDetailId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ShowDate")
    public Date getShowDate() {
        return this.showDate;
    }
    
    public void setShowDate(Date showDate) {
        this.showDate = showDate;
    }

    
    @Column(name="hallId", length=15)
    public String getHallId() {
        return this.hallId;
    }
    
    public void setHallId(String hallId) {
        this.hallId = hallId;
    }

    
    @Column(name="movieid", length=15)
    public String getMovieid() {
        return this.movieid;
    }
    
    public void setMovieid(String movieid) {
        this.movieid = movieid;
    }

    
    @Column(name="showtime", length=20)
    public String getShowtime() {
        return this.showtime;
    }
    
    public void setShowtime(String showtime) {
        this.showtime = showtime;
    }

    
    @Column(name="goldtype", length=30)
    public String getGoldtype() {
        return this.goldtype;
    }
    
    public void setGoldtype(String goldtype) {
        this.goldtype = goldtype;
    }

    
    @Column(name="goldnoofseats")
    public Integer getGoldnoofseats() {
        return this.goldnoofseats;
    }
    
    public void setGoldnoofseats(Integer goldnoofseats) {
        this.goldnoofseats = goldnoofseats;
    }

    
    @Column(name="goldprice")
    public Integer getGoldprice() {
        return this.goldprice;
    }
    
    public void setGoldprice(Integer goldprice) {
        this.goldprice = goldprice;
    }

    
    @Column(name="silvertype", length=30)
    public String getSilvertype() {
        return this.silvertype;
    }
    
    public void setSilvertype(String silvertype) {
        this.silvertype = silvertype;
    }

    
    @Column(name="silvernoofseats")
    public Integer getSilvernoofseats() {
        return this.silvernoofseats;
    }
    
    public void setSilvernoofseats(Integer silvernoofseats) {
        this.silvernoofseats = silvernoofseats;
    }

    
    @Column(name="silverprice")
    public Integer getSilverprice() {
        return this.silverprice;
    }
    
    public void setSilverprice(Integer silverprice) {
        this.silverprice = silverprice;
    }

    
    @Column(name="platinumtype", length=30)
    public String getPlatinumtype() {
        return this.platinumtype;
    }
    
    public void setPlatinumtype(String platinumtype) {
        this.platinumtype = platinumtype;
    }

    
    @Column(name="platinumnoofseats")
    public Integer getPlatinumnoofseats() {
        return this.platinumnoofseats;
    }
    
    public void setPlatinumnoofseats(Integer platinumnoofseats) {
        this.platinumnoofseats = platinumnoofseats;
    }

    
    @Column(name="platinumprice")
    public Integer getPlatinumprice() {
        return this.platinumprice;
    }
    
    public void setPlatinumprice(Integer platinumprice) {
        this.platinumprice = platinumprice;
    }

    
    @Column(name="remarks", length=50)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


