package com.movie.model;

// Generated Mar 31, 2014 2:57:31 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userbookdetails generated by hbm2java
 */
@Entity
@Table(name = "userbookdetails", catalog = "moviedb")
public class Userbookdetails implements java.io.Serializable {

	private String bookingId;
	private String uname;
	private String movieId;
	private String hallId;
	private String showDetailId;
	private String seatType;
	private String showTime;
	private Integer noOfSeat;
	private Double amount;
	private Date bdate;

	public Userbookdetails() {
	}

	public Userbookdetails(String bookingId, Date bdate) {
		this.bookingId = bookingId;
		this.bdate = bdate;
	}

	public Userbookdetails(String bookingId, String uname, String movieId,
			String hallId, String showDetailId, String seatType,
			String showTime, Integer noOfSeat, Double amount, Date bdate) {
		this.bookingId = bookingId;
		this.uname = uname;
		this.movieId = movieId;
		this.hallId = hallId;
		this.showDetailId = showDetailId;
		this.seatType = seatType;
		this.showTime = showTime;
		this.noOfSeat = noOfSeat;
		this.amount = amount;
		this.bdate = bdate;
	}

	@Id
	@Column(name = "bookingId", unique = true, nullable = false, length = 15)
	public String getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "uName", length = 20)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "movieId", length = 10)
	public String getMovieId() {
		return this.movieId;
	}

	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	@Column(name = "hallId", length = 10)
	public String getHallId() {
		return this.hallId;
	}

	public void setHallId(String hallId) {
		this.hallId = hallId;
	}

	@Column(name = "ShowDetailId", length = 15)
	public String getShowDetailId() {
		return this.showDetailId;
	}

	public void setShowDetailId(String showDetailId) {
		this.showDetailId = showDetailId;
	}

	@Column(name = "seatType", length = 10)
	public String getSeatType() {
		return this.seatType;
	}

	public void setSeatType(String seatType) {
		this.seatType = seatType;
	}

	@Column(name = "showTime", length = 20)
	public String getShowTime() {
		return this.showTime;
	}

	public void setShowTime(String showTime) {
		this.showTime = showTime;
	}

	@Column(name = "noOfSeat")
	public Integer getNoOfSeat() {
		return this.noOfSeat;
	}

	public void setNoOfSeat(Integer noOfSeat) {
		this.noOfSeat = noOfSeat;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bdate")
	public Date getBdate() {
		return this.bdate;
	}

	public void setBdate(Date bdate) {
		this.bdate = bdate;
	}

	@Override
	public String toString() {
		return "Userbookdetails [bookingId=" + bookingId + ", uname=" + uname
				+ ", movieId=" + movieId + ", hallId=" + hallId
				+ ", showDetailId=" + showDetailId + ", seatType=" + seatType
				+ ", showTime=" + showTime + ", noOfSeat=" + noOfSeat
				+ ", amount=" + amount + ", bdate=" + bdate + "]";
	}

}
